title: 行尸走肉
subtitle: "行尸走肉"
description: "行尸走肉, 行尸走肉论坛, 行尸走肉下载"
author: 行尸走肉
language: zh-cn
timezone: UTC
url: http://118.244.196.122
root: /
permalink: news/:year/:month/:day/:title/


public_dir: public
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:idany/idany.github.io.git

disqus_shortname: xingshizourou
google_analytics: UA-4910098-10
fb_admins: 100000247608790
swiftype_key: EwN4HMy_KMxTK_GMjV1z
twitter: 
github: xingshizourou/xingshizourou